package:
  version: '2.3.6p'
  version-code: 2306
  description:
  - 'Added a /react ping command for ping comparison'
  - 'Finally added text to the map graphs'
  - 'Bugfixes for the action controller'
  - 'Updated the client for better handling of lost connections'
