package:
  version: '4.1.3p'
  version-code: 4130
  description:
  - 'Fixed drop sample error'
  - 'Sampler performance improvements'
  - 'Added async tnt option (in worlds config)'
  - 'Added /re status command. Shows load distrobution'