package:
  version: '4.1.5p'
  version-code: 4150
  description:
  - 'Protocol changes to allow new client actions'
  - 'Added new language nodes'
  - 'Fixed issues with language startup'
  - 'Updated react splash text (see image)'
  - 'Various bugfixes related to performance'