package:
  version: '4.1.1p'
  version-code: 4110
  description:
  - 'Fixed update checking when its set to off again...'
  - 'Languages are now searched locally and loaded'
  - 'Fixed local language issues'