package:
  version: '4.0.9p'
  version-code: 4090
  description:
  - 'Tweaked display on entities for monitor'
  - 'Improved color selection for command help'
  - 'Performance improvements while monitoring'
  - 'Rendering fixes for maps (visual artifacts)'