package:
  version: '4.1.8p'
  version-code: 4180
  description:
  - 'Added drop countdown for removing drops (configurable)'
  - 'Added permissions in config.yml for remote users'
  - 'Loads of bugfixes and tweaks READ MORE ON SPIGOT!'