package:
  version: '2.8.1p'
  version-code: 2801
  description:
  - 'Fix issues with entity culling removing entities.'
  - 'Added a hard limit for culling per chunk.'
  - 'RECOMMENDED: DELETE reactions/action-cull-entities.yml'
