package:
  version: '2.5.2p'
  version-code: 2502
  description:
  - 'Compatability with Citizens & Chunk Purging. No more dead NPCs!'
  - 'Added Command Tabulation with next and previous buttons in chat.'
