package:
  version: '4.1.9p'
  version-code: 4190
  description:
  - 'Allow override of despawn rate in action-cull-entities'
  - 'Fixed console issue when reloading sometimes (and update fixing)'
  - 'Other various fixes and tweaks'