package:
  version: '4.1.6p'
  version-code: 4160
  description:
  - 'Various bugfixes around the plugin'
  - 'Chunk related mob limits not yet added (sorry)'
  - 'React Remote now supports the console!'