package:
  version: '2.6p'
  version-code: 2600
  description:
  - 'Added a NEW config for auto updating, and updating in general. The old configuration will do nothing'
  - 'Redesigned the way react updates, checks for updates, and auto updates'
  - 'If you have issues updating to this version from your current one, download it manually'
  - 'Bugfixes and other various improvements with commands and scheduled execution.'
