package:
  version: 4.3.3p
  version-code: 4330
  description:
  - Entities now display tags of their stack.
  - Name tags update and remove themselves from node tagging (invisible color tags)
  - Fixed stacking merge issue
