package:
  version: '2.4.9p'
  version-code: 2409
  description:
  - 'Dynamic Monitoring Tick Delays for faster timings'
  - 'Optimized Chunk counting for faster sampling'
  - 'Stored some information in memory instead of using the cpu often to determine it. (0.2ms increase on test server)'
