package:
  version: 4.3.4p
  version-code: 4340
  description:
  - Timings Processing is now much faster (on the cpu)
  - Added timings-controller setting max threads for multithreaded processing
  - Paperspigot now only takes 2 seconds to get the first batch of timings instead of 5 minutes
  - Improved performance while timings are off
