package:
  version: 4.3.2p
  version-code: 4320
  description:
  - Action Performance improvemtns
  - Fixed NPE while reading config
  - Fixed NPE for 1.9+ servers using stacking
  - Fixed log debugger spam
