package:
  version: '2.4p'
  version-code: 2400
  description:
  - 'Added world settings for per world configurations'
  - 'World Settings Feature: Fast-Fall for sand and gravel'
  - 'World Settings Feature: Fast-Decay for fast leaf decay'
