package:
  version: '3p'
  version-code: 3000
  description:
  - 'Many, Many bugfixes and performance improvements'
  - 'Added additional information for the dump file'
  - 'A few networking tweaks for client expansion'
  - 'Api tweaks'