package:
  version: '2.2.7p'
  version-code: 2207
  description:
  - 'Monitor information per player is now saved and used after reboots/login/logout'
  - 'Performance optimizations for timings & more'
