package:
  version: '3.2p'
  version-code: 3200
  description:
  - 'Monitoring now works with 1.11'
  - 'Monitoring should work for future versions'
  - 'Fixed reaction gui not working properly on 1.11'