package:
  version: '2.7.7p'
  version-code: 2707
  description:
  - 'Redesigned the way entitiy culling works.'
  - 'Recommended: Delete your old action-cull-entities then reconfigure it!'
  - 'Added a config version for all configs.'
  - 'Fixed an issue with tag colors not actually working.'
