package:
  version: '2.6.9p'
  version-code: 2609
  description:
  - 'Auto update now updates on restart (downloading live)'
  - 'You can turn back the live updater if you dont have issues with it in the updater.yml file'
  - 'Bugfixes for many entity related issues'
  - 'Performance tweaks to the sampler system'
