package:
  version: '4.1.7p'
  version-code: 4170
  description:
  - 'Added scoreboard interval to the main config.yml'
  - 'Added notification of mob culls (in action-cull-entities.yml)'
  - 'Added config for console hacks (needed for remote) console.yml'