package:
  version: 4.3.1p
  version-code: 4310
  description:
  - Mobs can now be un-stacked via action or by shift right clicking mobs.
  - Mobs now make pop sounds when stacking or unstacking
  - Mobs wont re-stack when split
  - Added the un-stack action to unstack all mobs
  - Added the re-stack action to re-stack unstacked mobs
