package:
  version: '4.2.1p'
  version-code: 4210
  description:
  - 'Various performance fixes and tweaks'
  - 'Fixed drop event error'
  - 'Fixed action bar error console spam'
  - 'Auto updater task will destroy itself if checking is off'