package:
  version: '2.6.5p'
  version-code: 2605
  description:
  - 'Stacked Mobs now should drop experience as intended'
  - 'Several Performance improvements for mob stacking aswell'
  - 'Fixed the ability to change the react tag with colors. (bottom of config.yml)'
