package:
  version: '2.7p'
  version-code: 2700
  description:
  - 'Added a method of monitoring via scoreboards (/re board) NOT PERFECTED YET'
  - 'Added additional placeholders for formatted sampler values instead of raw'
  - 'Bugfixes for some commands'
  - 'Performance improvements for the monitor controller'
