package:
  version: '2.7.4p'
  version-code: 2704
  description:
  - 'Fixed some errors from photon'
  - 'Fixed an issue with chunks not being calculated correctly'
  - 'Fixed several other data issues.'
