package:
  version: '2.5.10p'
  version-code: 2510
  description:
  - 'Defaulted Auto updating and checking to false. This will only affect new users'
  - 'Added some tweaks to the auto updater (plans to make a new reliable updater)'
