package:
  version: 4.2.8p
  version-code: 4280
  description:
  - Add Custom World Guard flags with /re rg. World guard + World Edit must be installed to use this.
  - 'Custom Flag: DENY_REACTIONS: Dont touch things in region'
  - 'Custom Flag: DENY_MONITORING: No Action bar monitor in region'
  - 'Custom Flag: DENY_MAPPING: No Maps in region'
