package:
  version: '2.8.3p'
  version-code: 2803
  description:
  - 'Photon no longer pops items out of chests (trapped also), hoppers, and anvils.'
  - 'Added a configurable option in the config.yml for title bolding (Off by default)'
  - 'Major performance tweaks for the monitor title.'
