package:
  version: '2.6.1p'
  version-code: 2601
  description:
  - 'Mob Stacking! Disabled by default, and still being worked on, stacks mobs together!'
  - 'We recommend you test this first before turning it on in your production environment'
  - 'Performance optimizations for many operations with players and samplers!'
