package:
  version: '4.0.7p'
  version-code: 4070
  description:
  - 'Drop caching removed until fixes can come'
  - 'Major performance improvement in event mapping'
  - 'Fixed react server crash from portscan'