package:
  version: '4.0.1p'
  version-code: 4010
  description:
  - 'Old configuration values are now auto pruned'
  - 'Redesigned entity culling'
  - '> Fixed culling on restricted entities'
  - '> Simplified culling for a max per chunk'
  - '> Culling is much faster cpu wise'
  
  