package:
  version: '2.6.3p'
  version-code: 2603
  description:
  - 'Mobs now stack correctly when chunks are loaded.'
  - 'Several performance improvements for startup time'
  - 'Fixed crash on linux systems'
