package:
  version: '4.0.2p'
  version-code: 4020
  description:
  - 'Mob Culling Overhaul!'
  - 'React will cull mobs hostile first (underground)'
  - 'React will cull mobs in darker lighting first'
  - 'Culling uses selective bias (configurable)'
  
  