package:
  version: '2.6.6p'
  version-code: 2606
  description:
  - 'Fix issue with protocol lib failing with react even though its not installed.'
  - 'Added the ability to change the permission denied message.'
