package:
  version: '2.8.6p'
  version-code: 2806
  description:
  - 'Fix many issues for several errors reported'
  - 'Added a small (expanding) api, documentation will be on the react page'
  - 'Performance improvements for startup.'
