package:
  version: '2.6.8p'
  version-code: 2608
  description:
  - 'Added a per-world option to assume-no-side-effects to entity types'
  - 'Added a per-world option to disable stacking for that world while stacking is enabled'
  - 'Tweaks to the entity stacker'
